window.VaultClassifierStrings = Object.freeze({
  "bridge.autoSave": "Changes save automatically.",
  "app.loading": "Loading Classifier…",
  "utility.close": "Close",
  "utility.settings.button": "Settings",
  "localModel.speedQuality": "Speed ↔ Quality",
  "localModel.speedQualityHint": "the model size used for tagging; download the selected tier before using it",
  "localModel.tier.fast.name": "Fast",
  "localModel.tier.fast.desc": "Smallest model; lowest memory requirement.",
  "localModel.tier.balanced.name": "Balanced",
  "localModel.tier.balanced.desc": "Medium-sized model; the default tier.",
  "localModel.tier.best.name": "Best",
  "localModel.tier.best.desc": "Largest model; highest memory requirement.",
  "localModel.tier.model": "{model} · {size} GB · needs {ram} GB RAM",
  "localModel.tier.ramShort": "This device has less than {ram} GB RAM — it may be slow or fail to load.",
  "localModel.tier.recommended": "RECOMMENDED FOR THIS DEVICE",
  "localModel.tier.sourceNote": "Model files download from Hugging Face when you choose Download.",
  "localModel.strictness": "Strict ↔ Broad",
  "localModel.strictnessHint": "default tag counts and how much confidence is required for additional tags",
  "localModel.strictness.1.name": "Strictest",
  "localModel.strictness.1.desc": "By default, up to one tag per item. Items may remain untagged.",
  "localModel.strictness.2.name": "Strict",
  "localModel.strictness.2.desc": "By default, up to three tags. Additional tags require very high confidence.",
  "localModel.strictness.3.name": "Balanced",
  "localModel.strictness.3.desc": "By default, up to three tags. Additional tags use the default confidence threshold.",
  "localModel.strictness.4.name": "Broad",
  "localModel.strictness.4.desc": "By default, up to three tags. Additional tags are accepted more readily.",
  "localModel.strictness.5.name": "Broadest",
  "localModel.strictness.5.desc": "By default, at least one and up to three tags. The same additional-tag threshold as Broad.",
  "localModel.tier.notDownloaded": "{name} (not downloaded)",
  "localModel.status.loaded": "LOADED",
  "localModel.status.loading": "LOADING",
  "localModel.status.disabled": "DISABLED",
  "localModel.status.no-model": "MODEL NOT DOWNLOADED",
  "localModel.status.failed": "LOAD FAILED",
  "modelLibrary.download": "Download",
  "modelLibrary.cancel": "Cancel",
  "modelLibrary.downloading": "Downloading {progress}",
  "modelLibrary.downloaded": "Downloaded",
  "modelLibrary.delete": "Delete",
  "research.title": "Web research",
  "research.status.on": "ENABLED",
  "research.status.off": "OFF",
  "research.copy": "Optional web lookups for content sources that remain hard to tag and terms you add without a description. Research requires consent and a configured provider.",
  "research.consent": "I consent to sending public source identifiers and requested terms to my selected research provider",
  "research.disclosure": "For web research, Vault sends a public source identifier or a term you added without a description to your selected provider, which searches the web. These research requests do not include content titles, summaries, body text, or private source IDs.",
  "research.chooseProvider": "Choose a provider",
  "research.llmProvider": "Research provider",
  "research.llmProviderHint": "must support built-in web search (OpenAI, Gemini, or Anthropic)",
  "research.fetchModels": "Fetch model list",
  "research.fetchingModels": "Fetching models…",
  "research.refreshModels": "Refresh model list",
  "research.retryModels": "Retry",
  "research.chooseModel": "Choose a model",
  "research.modelSearch": "Search models",
  "research.noMatchingModels": "No matching models",
  "research.noModels": "No models returned. Try refreshing the list.",
  "research.savedModel": "Saved model: {model}",
  "research.modelUnavailable": "Unavailable in fetched list",
  "research.modelProviderRequired": "Choose a provider first.",
  "research.modelKeyRequired": "Add the provider’s API key to fetch its models.",
  "research.model": "Research model",
  "research.modelHint": "model used by the research provider",
  "research.usageToday": "Research tokens used today: {used} of {limit}",
  "research.constantsNote": "Research is limited to 6 lookups per minute and 10,000 tokens per day. Repeated tagging difficulties trigger a source lookup when its score reaches 3; the score halves every 14 days. Saved knowledge has no automatic expiry.",
  "research.status.heading": "Research status",
  "research.status.queue": "{pending} queued · {inCooldown} waiting to retry ({transient} temporary failures) · this session: {succeeded} completed, {failed} failed, {retries} automatic retries, {skippedBudget} delayed by the token limit",
  "research.status.inFlight": "Researching now: {subject}",
  "research.status.lastFailure": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); next attempt allowed in {retry}",
  "research.status.lastFailure.due": "Last failure: {kind} on “{subject}” {ago} ago (failure #{count}); retry allowed now",
  "research.status.noFailures": "No research failures recorded.",
  "research.status.retryNow": "Retry failed lookups",
  "research.status.retryNowHint": "resets retry delays and queues failed lookups from this session",
  "research.failure.timeout": "timed out",
  "research.failure.network": "network error",
  "research.failure.rateLimited": "rate limited",
  "research.failure.serverError": "provider server error",
  "research.failure.providerRejected": "provider rejected the request",
  "research.failure.invalidConfiguration": "invalid research configuration",
  "research.failure.emptyResponse": "empty provider response",
  "research.failure.unknown": "unknown error",
  "navigation.aria": "Classifier workspaces",
  "navigation.resize": "Resize classifier navigation",
  "navigation.title": "Classifier",
  "navigation.subtitle": "On-device tagging",
  "navigation.work": "Work",
  "navigation.control": "Control",
  "navigation.backup": "Local backup",
  "navigation.backupMeta": "Private snapshots",
  "navigation.integration": "Browser bridge",
  "navigation.integrationMeta": "Not installed",
  "navigation.seedVerified": "Seed package verified",
  "navigation.seedCopy": "No endpoint, account, or automatic task is configured.",
  "navigation.classifierTypes": "Classifier groups",
  "navigation.apiKeys": "API keys",
  "navigation.apiKeysMeta": "Provider configurations",
  "navigation.newType": "New group",
  "navigation.noTypes": "No classifier groups yet. Create one and choose its platforms.",
  "navigation.moveUp": "Move up",
  "navigation.moveDown": "Move down",
  "navigation.dragReorder": "Drag to reorder",
  "createType.title": "New classifier group",
  "createType.copy": "A group tags its platforms with its own tag tree; a platform belongs to one group. Choose its platforms now—they cannot be changed after creation. It starts with Balanced model settings and no tagging instructions.",
  "createType.platformLabel": "Platforms",
  "createType.platformRequired": "Select at least one platform.",
  "createType.nameLabel": "Group name",
  "createType.create": "Create group",
  "createType.defaultName": "New group",
  "bridge.tabTree": "Tag tree",
  "settings.apiKeysTitle": "API keys & providers",
  "settings.apiKeysCopy": "Provider configurations for web research and platform data.",
  "settings.manageApiKeys": "Manage API keys",
  "enum.action.allow": "Allow",
  "enum.action.dim": "Dim",
  "enum.action.block": "Block",
  "enum.surface.feed": "Feed",
  "enum.surface.page": "Page",
  "enum.effort.minimal": "Minimal",
  "enum.effort.low": "Low",
  "enum.effort.medium": "Medium",
  "enum.effort.high": "High",
  "enum.selection.targetedFalseAllow": "Risk selected",
  "enum.selection.targetedWithRandomSample": "Risk + sample",
  "enum.selection.userMarkedOnly": "Only marked",
  "enum.grade.correctAllow": "Correct allow",
  "enum.grade.correctDimBlock": "Correct dim or block",
  "enum.grade.falseAllow": "False allow",
  "enum.grade.falseDim": "False dim",
  "enum.grade.falseBlock": "False block",
  "enum.grade.insufficientEvidence": "Insufficient evidence",
  "enum.intent.potentialFalseAllow": "Potential false allow",
  "enum.intent.userMarked": "User marked",
  "enum.finding.potentialFalseAllow": "Potential false allow",
  "enum.finding.noIssue": "No issue",
  "common.delete": "Delete",
  "common.clickAgainToDelete": "Click again to delete",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "backup.title": "Local model backup",
  "backup.copy": "Keep private copies of this device's settings, taxonomy, and collected workspace configuration. Nothing is uploaded or shared.",
  "common.on": "ON",
  "common.off": "OFF",
  "backup.ownerGate": "Owner gate",
  "backup.ownerCopy": "The owner-code verifier stays in protected storage on this device. The code itself is never written to state or a backup.",
  "backup.unlocked": "Backup controls are unlocked for this app session.",
  "backup.ownerCode": "Owner code",
  "backup.existingCode": "Enter existing code",
  "backup.newCode": "Create 8+ character code",
  "backup.unlock": "Unlock",
  "backup.setCode": "Set code",
  "backup.folder": "Private snapshot folder",
  "backup.folderCopy": "Retains the current local snapshot plus three previous snapshots.",
  "backup.localFolder": "Local folder",
  "backup.pathHint": "A path you control",
  "backup.auto": "Back up after local configuration changes",
  "backup.create": "Create backup now",
  "integration.title": "Browser bridge",
  "integration.copy": "The Chrome and Edge adapter requires registered Native Messaging authentication.",
  "integration.notInstalled": "NOT INSTALLED",
  "integration.app": "App classifier",
  "integration.ready": "Ready locally",
  "integration.pairing": "Local authentication",
  "integration.keychain": "Keychain-backed proof",
  "integration.host": "Native host",
  "integration.notRegistered": "Requires installer registration",
  "integration.server": "Protocol",
  "integration.notRequired": "Version 4",
  "integration.notice": "A signed installer must supply confirmed stable extension IDs and the host path. Until then, Chrome and Edge stay disconnected rather than using an unauthenticated bridge.",
  "navigation.llmAssist": "API providers",
  "navigation.llmAssistMeta": "Provider configurations",
  "navigation.browserBridge": "Classifier groups",
  "navigation.browserBridgeMeta": "Tagging settings",
  "navigation.more": "More",
  "bridge.overrides.houseRules": "Tagging instructions",
  "navigation.knowledge": "Knowledge",
  "navigation.knowledgeMeta": "Content sources & terms",
  "navigation.localProfile": "Local profile",
  "navigation.assetCopy": "Your trees, models, data, bridge, and provider usage remain under local control.",
  "tree.nodeName": "Tag name",
  "tree.contextHint": "Click or right-click to edit this tag",
  "tree.createNode": "Create tag",
  "tree.editNode": "Edit tag",
  "tree.cancel": "Cancel",
  "tree.connectionHint": "Select a tag to make it the parent.",
  "tree.connection": "Set parent",
  "tree.disconnection": "Remove parent",
  "tree.deleteNode": "Delete tag",
  "tree.rearrange": "Rearrange",
  "tree.canvasHint": "Right-click empty space to create a root tag. Click or right-click a tag to edit it. Drag a tag to move its branch.",
  "tree.empty": "No tags in this tree yet.",
  "tree.tagName": "Tag name",
  "tree.tagDescription": "Tag description",
  "tree.tagDescriptionCopy": "Optional context supplied to the local model when this tag is eligible for classification.",
  "llm.title": "API providers",
  "llm.copy": "Configure providers for web research and platform data.",
  "llm.localOnlyDisclosure": "API keys are stored in this app’s support folder on this device, not in the system Keychain. Keys are sent to the configured provider to authenticate requests; Vault does not upload them to its own server.",
  "llm.keyLibrary": "Providers",
  "llm.providerType": "Provider type",
  "llm.chooseProviderType": "Choose a provider type",
  "llm.createKey": "Add provider",
  "llm.createCopy": "Choose a model provider, a platform data API, or a compatible custom endpoint.",
  "llm.empty": "No providers configured. Choose a provider type, then add its configuration.",
  "llm.providerPanel": "Provider settings",
  "llm.provider.openAI": "OpenAI",
  "llm.provider.openAICompatible": "OpenAI-compatible API",
  "llm.provider.deepSeek": "DeepSeek",
  "llm.provider.gemini": "Gemini",
  "llm.provider.anthropic": "Anthropic",
  "llm.provider.mistral": "Mistral AI",
  "llm.provider.cohere": "Cohere",
  "llm.provider.groq": "Groq",
  "llm.provider.openRouter": "OpenRouter",
  "llm.provider.ollama": "Ollama",
  "llm.provider.youtubeData": "YouTube Data API",
  "llm.provider.twitch": "Twitch",
  "llm.provider.reddit": "Reddit",
  "llm.provider.xPlatform": "X API",
  "llm.provider.instagramGraph": "Instagram Graph API",
  "llm.provider.facebookGraph": "Facebook Graph API",
  "llm.retiredSearchProvider": "This search provider is inactive. Web research now uses a model provider with built-in web search. You can delete this saved configuration.",
  "llm.provider.serper": "Serper",
  "llm.provider.youSearch": "You.com Search",
  "llm.provider.custom": "Custom API",
  "llm.providerGroup.models": "Language models",
  "llm.providerGroup.platform": "Platform data APIs",
  "llm.providerGroup.custom": "Custom and compatible APIs",
  "llm.deleteProfile": "Delete provider",
  "llm.apiKeyOrToken": "API key or token",
  "llm.apiEndpoint": "API endpoint",
  "llm.testModel": "Model for test",
  "llm.test": "Test connection",
  "llm.testing": "Testing…",
  "llm.testSucceeded": "Connection test succeeded.",
  "llm.tokenUsage": "Token usage",
  "llm.tokenTotal": "{total} tokens in total",
  "llm.apiCalls": "API calls",
  "llm.responseShape": "Last response format error",
  "llm.protocol.accountID": "Account ID",
  "llm.protocol.apiVersion": "API version",
  "llm.protocol.clientID": "Client ID",
  "llm.protocol.location": "Location",
  "llm.protocol.projectID": "Project ID",
  "llm.protocol.region": "Region",
  "llm.protocol.userAgent": "User agent",
  "llm.protocol.searchEngineID": "Search engine ID",
  "llm.protocol.protocolFamily": "Request family",
  "bridge.title": "Classifier groups",
  "bridge.copy": "Each group tags its platforms using its own tag tree, model settings, and additional instructions.",
  "bridge.typeLibrary": "Classifier groups",
  "bridge.typePanel": "Classifier group",
  "bridge.newTypeName": "New classifier group",
  "bridge.newTypeNameCopy": "For example, YouTube creator focus",
  "bridge.createType": "Create group",
  "bridge.emptyTypes": "Create a classifier group to start tagging content.",
  "bridge.selectType": "Select a classifier group on the left, or choose New group.",
  "bridge.typeName": "Group name",
  "bridge.saveType": "Save group",
  "bridge.deleteType": "Delete group",
  "classification.title": "Content tagging",
  "classification.enabled": "Enable tagging",
  "classification.copy": "Tag content on platforms assigned to active Classifier groups. Blocking filters and their schedules do not control tagging.",
  "classification.pause": "Pause tagging",
  "classification.resume": "Resume tagging",
  "classification.paused": "Paused",
  "classification.disabled": "Disabled in Settings",
  "classification.active": "Active",
  "bridge.applicablePlatform": "Platforms",
  "bridge.platformTakenBy": "in {name}",
  "bridge.platformsFixed": "Platforms are fixed when the group is created.",
  "common.cancel": "Cancel",
  "bridge.noApplicablePlatform": "Choose a platform",
  "bridge.platformDataBound": "Platform data provider: {profile}",
  "bridge.platformDataMissingKey": "No {platform} API key is configured on this device.",
  "bridge.recordingOff": "Recording is off for this platform (Activity → Recording), so it isn't tagged.",
  "bridge.localModel": "Local model",
  "bridge.localModelCopy": "These model settings and tagging instructions apply only to this group. Model downloads are shared across groups.",
  "bridge.tagBounds.minimum": "Minimum tags",
  "bridge.tagBounds.maximum": "Maximum tags",
  "bridge.tagBounds.minimumHint": "0–3 tags per item; 0 allows untagged content",
  "bridge.tagBounds.maximumHint": "1–3 tags per item",
  "bridge.tagBounds.copy": "Leave a field empty to use its Strict ↔ Broad default. Default minimum: {minimum}; default maximum: {maximum}.",
  "bridge.tagBounds.precedence": "Custom tag counts in More replace the dial’s default counts. Strict ↔ Broad still sets the confidence required for additional tags.",
  "bridge.tagBounds.default": "Tag counts follow Strict ↔ Broad",
  "bridge.tagBounds.custom": "Tag counts: {minimum}–{maximum}",
  "bridge.tagBounds.error": "Use whole numbers: Minimum 0–3, Maximum 1–3. Minimum must not exceed Maximum, including values supplied by Strict ↔ Broad.",
  "bridge.localModelHouseRules": "Tagging instructions",
  "bridge.localModelHouseRulesCopy": "optional instructions for tagging in this group; leave empty for no additional instructions",
  "bridge.localModelResidentNote": "Groups using the same tier share one loaded model. Up to two model tiers stay loaded at once.",
  "bridge.researchOverrides": "Web research",
  "bridge.researchOverridesCopy": "Allow web research for this group’s content sources and terms.",
  "research.setup": "Set up web research…",
  "research.enable": "Enable web research…",
  "research.configure": "Configure web research",
  "research.noProvider": "No provider selected",
  "research.status.setup": "Setup needed",
  "knowledge.lookupProvider": "Research provider",
  "bridge.researchMode": "Research for this group",
  "bridge.researchMode.inherit": "Follow Settings",
  "bridge.researchMode.on": "On",
  "bridge.researchMode.off": "Off",
  "bridge.researchMasterGate": "Research consent in Settings applies to every group. Research is unavailable while consent is off.",
  "bridge.notTag": "Not",
  "bridge.platform": "Platform binding",
  "bridge.platformCopy": "One platform selects one active tree, dataset, and compatible model.",
  "bridge.none": "No bridge platform",
  "bridge.assetBinding": "Asset binding",
  "bridge.oneTreeDataset": "One active tree + dataset",
  "bridge.configure": "Configure locally",
  "knowledge.title": "Knowledge",
  "knowledge.copy": "Short descriptions of content sources and terms used by the local tagging model. Source descriptions accompany their content; term descriptions apply when the term appears in a title.",
  "knowledge.badge": "On-device",
  "knowledge.disclosure": "Descriptions are stored on this device and used by the local tagging model. Keep them short to reduce processing time. Editing a source description affects future tagging of its content. Deleted source knowledge can be researched again.",
  "knowledge.creators": "Content sources",
  "knowledge.creatorsHint": "Sources include creators, accounts, channels, and communities. Add them yourself or let repeated tagging difficulties trigger web research.",
  "knowledge.terms": "Known terms",
  "knowledge.termsHint": "Terms you added, shared across platforms and used when they appear in content titles.",
  "knowledge.addTerm": "Add a term",
  "knowledge.addTermHint": "A game, show, person, server, or other term the model may not know. Leave the description empty to request web research.",
  "knowledge.termSubject": "Term",
  "knowledge.termSubjectHint": "as it appears in content titles",
  "knowledge.termMeaningPlaceholder": "Optional — what it is, in a sentence",
  "knowledge.addTermButton": "Add term",
  "knowledge.addCreator": "Add a content source",
  "knowledge.addCreatorHint": "A creator, channel, account, or community. Leave the description empty to request web research.",
  "knowledge.platform": "Platform",
  "knowledge.creator": "Content source",
  "knowledge.creatorHint": "a profile link, @handle, Reddit r/name, or a source name already seen",
  "knowledge.creatorMeaningPlaceholder": "Optional — what they post, in a sentence",
  "knowledge.addCreatorButton": "Add source",
  "knowledge.creatorsOn": "Content sources · {platform}",
  "knowledge.search": "Search knowledge",
  "knowledge.byYou": "By you",
  "knowledge.lookedUp": "Researched",
  "knowledge.description": "Description",
  "knowledge.delete": "Delete",
  "knowledge.empty": "Nothing here yet.",
  "dictionary.connectionTitle": "Dictionary",
  "dictionary.fullSummary": "Full download · {count} entries",
  "dictionary.lookupSummary": "Cache + online lookup · {count} cached",
  "dictionary.updateStatus": "Update available",
  "dictionary.installed": "Installed",
  "dictionary.termSummary": "Terms · {count} entries · {version}",
  "dictionary.creatorSummary": "Creators · {summary} · {version}",
  "dictionary.configure": "Configure dictionaries",
  "dictionary.entries": "{count} entries · {version}{update}",
  "dictionary.notDownloaded": "Not downloaded",
  "dictionary.updateAvailable": " · Update available",
  "dictionary.updateCache": "Update cache version",
  "dictionary.download": "Download / Update",
  "dictionary.title": "Official dictionaries",
  "dictionary.priority": "Your own descriptions and AI-researched descriptions always take priority.",
  "dictionary.working": "Working…",
  "dictionary.checkUpdates": "Check for updates",
  "dictionary.terms": "Terms",
  "dictionary.creators": "Creators",
  "dictionary.creatorMode": "Creator dictionary",
  "dictionary.cacheMode": "Cache + online lookup",
  "dictionary.fullMode": "Full download · offline lookup",
  "dictionary.cacheMaximum": "Maximum cached creators",
  "dictionary.helpImprove": "Help improve the creator dictionary",
  "dictionary.sharingExplanation": "Occasionally send missing public creator IDs and available subscriber/follower counts. No term names, titles, history or personal descriptions. Maximum 50 submissions/day; server retention 7 days. Turn this off anytime.",
  "dictionary.cacheSummary": "{count} creators cached. Full packs stay indexed on disk; only matching descriptions enter tagging. {guidance}",
  "dictionary.fullDownloadRequired": "Download Creators to enable full offline lookup.",
  "dictionary.importExport": "Import / export your dictionary",
  "dictionary.personalJSON": "Personal dictionary JSON",
  "dictionary.openJSON": "Open JSON file",
  "dictionary.import": "Import",
  "dictionary.export": "Export JSON",
  "dictionary.exported": "Exported personal dictionary",
  "dictionary.copy": "Copy JSON",
  "dictionary.contributionTitle": "Creator dictionary contribution",
  "dictionary.webContributionBody": "Vault can occasionally send public creator IDs and their available subscriber/follower counts to our server. No titles, term names, browsing history or personal definitions are sent. You can disable this anytime in Settings.",
  "dictionary.share": "Share creator IDs and subscriber counts",
  "dictionary.retention": "Maximum 50/day; retained for 7 days. See the Privacy Policy for details.",
  "dictionary.saveChoice": "Save choice",
  "dictionary.decline": "Don’t share",
});
